export const PRODUCT_SEED_DATA = [
  {
    id: 'ropa-001',
    name: 'IMG-20260305-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260305-WA0006.jpg',
  },
  {
    id: 'ropa-002',
    name: 'IMG-20260311-WA0055',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260311-WA0055.jpg',
  },
  {
    id: 'ropa-003',
    name: 'IMG-20260312-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260312-WA0006.jpg',
  },
  {
    id: 'ropa-004',
    name: 'IMG-20260331-WA0002',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0002.jpg',
  },
  {
    id: 'ropa-005',
    name: 'IMG-20260331-WA0003',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0003.jpg',
  },
  {
    id: 'ropa-006',
    name: 'IMG-20260331-WA0004',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0004.jpg',
  },
  {
    id: 'ropa-007',
    name: 'IMG-20260331-WA0005',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0005.jpg',
  },
  {
    id: 'ropa-008',
    name: 'IMG-20260331-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0006.jpg',
  },
  {
    id: 'ropa-009',
    name: 'IMG-20260331-WA0008',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0008.jpg',
  },
  {
    id: 'ropa-010',
    name: 'IMG-20260331-WA0009',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0009.jpg',
  },
  {
    id: 'ropa-011',
    name: 'IMG-20260331-WA0010',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0010.jpg',
  },
  {
    id: 'ropa-012',
    name: 'IMG-20260331-WA0011',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0011.jpg',
  },
  {
    id: 'ropa-013',
    name: 'IMG-20260331-WA0012',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0012.jpg',
  },
  {
    id: 'ropa-014',
    name: 'IMG-20260331-WA0013',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0013.jpg',
  },
  {
    id: 'ropa-015',
    name: 'IMG-20260331-WA0014',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0014.jpg',
  },
  {
    id: 'ropa-016',
    name: 'IMG-20260331-WA0015',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0015.jpg',
  },
  {
    id: 'ropa-017',
    name: 'IMG-20260331-WA0016',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0016.jpg',
  },
  {
    id: 'ropa-018',
    name: 'IMG-20260331-WA0020',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0020.jpg',
  },
  {
    id: 'ropa-019',
    name: 'IMG-20260331-WA0021',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0021.jpg',
  },
  {
    id: 'ropa-020',
    name: 'IMG-20260331-WA0022',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0022.jpg',
  },
  {
    id: 'ropa-021',
    name: 'IMG-20260331-WA0023',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0023.jpg',
  },
  {
    id: 'ropa-022',
    name: 'IMG-20260331-WA0024',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260331-WA0024.jpg',
  },
  {
    id: 'ropa-023',
    name: 'IMG-20260401-WA0044',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260401-WA0044.jpg',
  },
  {
    id: 'ropa-024',
    name: 'IMG-20260402-WA0004',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260402-WA0004.jpg',
  },
  {
    id: 'ropa-025',
    name: 'IMG-20260402-WA0005',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260402-WA0005.jpg',
  },
  {
    id: 'ropa-026',
    name: 'IMG-20260402-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260402-WA0006.jpg',
  },
  {
    id: 'ropa-027',
    name: 'IMG-20260406-WA0004',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260406-WA0004.jpg',
  },
  {
    id: 'ropa-028',
    name: 'IMG-20260406-WA0005',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260406-WA0005.jpg',
  },
  {
    id: 'ropa-029',
    name: 'IMG-20260406-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260406-WA0006.jpg',
  },
  {
    id: 'ropa-030',
    name: 'IMG-20260407-WA0050',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260407-WA0050.jpg',
  },
  {
    id: 'ropa-031',
    name: 'IMG-20260408-WA0000',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0000.jpg',
  },
  {
    id: 'ropa-032',
    name: 'IMG-20260408-WA0001',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0001.jpg',
  },
  {
    id: 'ropa-033',
    name: 'IMG-20260408-WA0002',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0002.jpg',
  },
  {
    id: 'ropa-034',
    name: 'IMG-20260408-WA0003',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0003.jpg',
  },
  {
    id: 'ropa-035',
    name: 'IMG-20260408-WA0004',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0004.jpg',
  },
  {
    id: 'ropa-036',
    name: 'IMG-20260408-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0006.jpg',
  },
  {
    id: 'ropa-037',
    name: 'IMG-20260408-WA0008',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260408-WA0008.jpg',
  },
  {
    id: 'ropa-038',
    name: 'IMG-20260410-WA0001',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0001.jpg',
  },
  {
    id: 'ropa-039',
    name: 'IMG-20260410-WA0002',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0002.jpg',
  },
  {
    id: 'ropa-040',
    name: 'IMG-20260410-WA0003',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0003.jpg',
  },
  {
    id: 'ropa-041',
    name: 'IMG-20260410-WA0004',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0004.jpg',
  },
  {
    id: 'ropa-042',
    name: 'IMG-20260410-WA0005',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0005.jpg',
  },
  {
    id: 'ropa-043',
    name: 'IMG-20260410-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0006.jpg',
  },
  {
    id: 'ropa-044',
    name: 'IMG-20260410-WA0007',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0007.jpg',
  },
  {
    id: 'ropa-045',
    name: 'IMG-20260410-WA0008',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0008.jpg',
  },
  {
    id: 'ropa-046',
    name: 'IMG-20260410-WA0009',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0009.jpg',
  },
  {
    id: 'ropa-047',
    name: 'IMG-20260410-WA0010',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0010.jpg',
  },
  {
    id: 'ropa-048',
    name: 'IMG-20260410-WA0011',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0011.jpg',
  },
  {
    id: 'ropa-049',
    name: 'IMG-20260410-WA0012',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0012.jpg',
  },
  {
    id: 'ropa-050',
    name: 'IMG-20260410-WA0013',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0013.jpg',
  },
  {
    id: 'ropa-051',
    name: 'IMG-20260410-WA0014',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0014.jpg',
  },
  {
    id: 'ropa-052',
    name: 'IMG-20260410-WA0015',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0015.jpg',
  },
  {
    id: 'ropa-053',
    name: 'IMG-20260410-WA0016',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0016.jpg',
  },
  {
    id: 'ropa-054',
    name: 'IMG-20260410-WA0017',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0017.jpg',
  },
  {
    id: 'ropa-055',
    name: 'IMG-20260410-WA0018',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0018.jpg',
  },
  {
    id: 'ropa-056',
    name: 'IMG-20260410-WA0019',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0019.jpg',
  },
  {
    id: 'ropa-057',
    name: 'IMG-20260410-WA0020',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0020.jpg',
  },
  {
    id: 'ropa-058',
    name: 'IMG-20260410-WA0021',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0021.jpg',
  },
  {
    id: 'ropa-059',
    name: 'IMG-20260410-WA0022',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0022.jpg',
  },
  {
    id: 'ropa-060',
    name: 'IMG-20260410-WA0026',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0026.jpg',
  },
  {
    id: 'ropa-061',
    name: 'IMG-20260410-WA0027',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0027.jpg',
  },
  {
    id: 'ropa-062',
    name: 'IMG-20260410-WA0028',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0028.jpg',
  },
  {
    id: 'ropa-063',
    name: 'IMG-20260410-WA0030',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0030.jpg',
  },
  {
    id: 'ropa-064',
    name: 'IMG-20260410-WA0031',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0031.jpg',
  },
  {
    id: 'ropa-065',
    name: 'IMG-20260410-WA0033',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0033.jpg',
  },
  {
    id: 'ropa-066',
    name: 'IMG-20260410-WA0035',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0035.jpg',
  },
  {
    id: 'ropa-067',
    name: 'IMG-20260410-WA0037',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0037.jpg',
  },
  {
    id: 'ropa-068',
    name: 'IMG-20260410-WA0038',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0038.jpg',
  },
  {
    id: 'ropa-069',
    name: 'IMG-20260410-WA0039',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0039.jpg',
  },
  {
    id: 'ropa-070',
    name: 'IMG-20260410-WA0040',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0040.jpg',
  },
  {
    id: 'ropa-071',
    name: 'IMG-20260410-WA0041',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0041.jpg',
  },
  {
    id: 'ropa-072',
    name: 'IMG-20260410-WA0042',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0042.jpg',
  },
  {
    id: 'ropa-073',
    name: 'IMG-20260410-WA0043',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0043.jpg',
  },
  {
    id: 'ropa-074',
    name: 'IMG-20260410-WA0044',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0044.jpg',
  },
  {
    id: 'ropa-075',
    name: 'IMG-20260410-WA0045',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0045.jpg',
  },
  {
    id: 'ropa-076',
    name: 'IMG-20260410-WA0046',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0046.jpg',
  },
  {
    id: 'ropa-077',
    name: 'IMG-20260410-WA0047',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0047.jpg',
  },
  {
    id: 'ropa-078',
    name: 'IMG-20260410-WA0048',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0048.jpg',
  },
  {
    id: 'ropa-079',
    name: 'IMG-20260410-WA0049',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0049.jpg',
  },
  {
    id: 'ropa-080',
    name: 'IMG-20260410-WA0050',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0050.jpg',
  },
  {
    id: 'ropa-081',
    name: 'IMG-20260410-WA0051',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0051.jpg',
  },
  {
    id: 'ropa-082',
    name: 'IMG-20260410-WA0052',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0052.jpg',
  },
  {
    id: 'ropa-083',
    name: 'IMG-20260410-WA0053',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0053.jpg',
  },
  {
    id: 'ropa-084',
    name: 'IMG-20260410-WA0054',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0054.jpg',
  },
  {
    id: 'ropa-085',
    name: 'IMG-20260410-WA0055',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0055.jpg',
  },
  {
    id: 'ropa-086',
    name: 'IMG-20260410-WA0056',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0056.jpg',
  },
  {
    id: 'ropa-087',
    name: 'IMG-20260410-WA0057',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0057.jpg',
  },
  {
    id: 'ropa-088',
    name: 'IMG-20260410-WA0058',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0058.jpg',
  },
  {
    id: 'ropa-089',
    name: 'IMG-20260410-WA0059',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0059.jpg',
  },
  {
    id: 'ropa-090',
    name: 'IMG-20260410-WA0060',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0060.jpg',
  },
  {
    id: 'ropa-091',
    name: 'IMG-20260410-WA0061',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0061.jpg',
  },
  {
    id: 'ropa-092',
    name: 'IMG-20260410-WA0062',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0062.jpg',
  },
  {
    id: 'ropa-093',
    name: 'IMG-20260410-WA0063',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0063.jpg',
  },
  {
    id: 'ropa-094',
    name: 'IMG-20260410-WA0064',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0064.jpg',
  },
  {
    id: 'ropa-095',
    name: 'IMG-20260410-WA0065',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0065.jpg',
  },
  {
    id: 'ropa-096',
    name: 'IMG-20260410-WA0066',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0066.jpg',
  },
  {
    id: 'ropa-097',
    name: 'IMG-20260410-WA0067',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0067.jpg',
  },
  {
    id: 'ropa-098',
    name: 'IMG-20260410-WA0068',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0068.jpg',
  },
  {
    id: 'ropa-099',
    name: 'IMG-20260410-WA0069',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0069.jpg',
  },
  {
    id: 'ropa-100',
    name: 'IMG-20260410-WA0070',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0070.jpg',
  },
  {
    id: 'ropa-101',
    name: 'IMG-20260410-WA0071',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0071.jpg',
  },
  {
    id: 'ropa-102',
    name: 'IMG-20260410-WA0072',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0072.jpg',
  },
  {
    id: 'ropa-103',
    name: 'IMG-20260410-WA0073',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0073.jpg',
  },
  {
    id: 'ropa-104',
    name: 'IMG-20260410-WA0074',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0074.jpg',
  },
  {
    id: 'ropa-105',
    name: 'IMG-20260410-WA0075',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0075.jpg',
  },
  {
    id: 'ropa-106',
    name: 'IMG-20260410-WA0076',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0076.jpg',
  },
  {
    id: 'ropa-107',
    name: 'IMG-20260410-WA0077',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0077.jpg',
  },
  {
    id: 'ropa-108',
    name: 'IMG-20260410-WA0078',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0078.jpg',
  },
  {
    id: 'ropa-109',
    name: 'IMG-20260410-WA0079',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0079.jpg',
  },
  {
    id: 'ropa-110',
    name: 'IMG-20260410-WA0082',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0082.jpg',
  },
  {
    id: 'ropa-111',
    name: 'IMG-20260410-WA0083',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0083.jpg',
  },
  {
    id: 'ropa-112',
    name: 'IMG-20260410-WA0084',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0084.jpg',
  },
  {
    id: 'ropa-113',
    name: 'IMG-20260410-WA0085',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0085.jpg',
  },
  {
    id: 'ropa-114',
    name: 'IMG-20260410-WA0086',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0086.jpg',
  },
  {
    id: 'ropa-115',
    name: 'IMG-20260410-WA0087',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0087.jpg',
  },
  {
    id: 'ropa-116',
    name: 'IMG-20260410-WA0088',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0088.jpg',
  },
  {
    id: 'ropa-117',
    name: 'IMG-20260410-WA0089',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0089.jpg',
  },
  {
    id: 'ropa-118',
    name: 'IMG-20260410-WA0090',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0090.jpg',
  },
  {
    id: 'ropa-119',
    name: 'IMG-20260410-WA0091',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0091.jpg',
  },
  {
    id: 'ropa-120',
    name: 'IMG-20260410-WA0092',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0092.jpg',
  },
  {
    id: 'ropa-121',
    name: 'IMG-20260410-WA0093',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0093.jpg',
  },
  {
    id: 'ropa-122',
    name: 'IMG-20260410-WA0094',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0094.jpg',
  },
  {
    id: 'ropa-123',
    name: 'IMG-20260410-WA0097',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260410-WA0097.jpg',
  },
  {
    id: 'ropa-124',
    name: 'IMG-20260413-WA0006',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0006.jpg',
  },
  {
    id: 'ropa-125',
    name: 'IMG-20260413-WA0008',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0008.jpg',
  },
  {
    id: 'ropa-126',
    name: 'IMG-20260413-WA0009',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0009.jpg',
  },
  {
    id: 'ropa-127',
    name: 'IMG-20260413-WA0010',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0010.jpg',
  },
  {
    id: 'ropa-128',
    name: 'IMG-20260413-WA0012',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0012.jpg',
  },
  {
    id: 'ropa-129',
    name: 'IMG-20260413-WA0013',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0013.jpg',
  },
  {
    id: 'ropa-130',
    name: 'IMG-20260413-WA0015',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0015.jpg',
  },
  {
    id: 'ropa-131',
    name: 'IMG-20260413-WA0017',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0017.jpg',
  },
  {
    id: 'ropa-132',
    name: 'IMG-20260413-WA0019',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0019.jpg',
  },
  {
    id: 'ropa-133',
    name: 'IMG-20260413-WA0022',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0022.jpg',
  },
  {
    id: 'ropa-134',
    name: 'IMG-20260413-WA0023',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0023.jpg',
  },
  {
    id: 'ropa-135',
    name: 'IMG-20260413-WA0025',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0025.jpg',
  },
  {
    id: 'ropa-136',
    name: 'IMG-20260413-WA0031',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0031.jpg',
  },
  {
    id: 'ropa-137',
    name: 'IMG-20260413-WA0032',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0032.jpg',
  },
  {
    id: 'ropa-138',
    name: 'IMG-20260413-WA0033',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0033.jpg',
  },
  {
    id: 'ropa-139',
    name: 'IMG-20260413-WA0034',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0034.jpg',
  },
  {
    id: 'ropa-140',
    name: 'IMG-20260413-WA0035',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧤',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0035.jpg',
  },
  {
    id: 'ropa-141',
    name: 'IMG-20260413-WA0036',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👗',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0036.jpg',
  },
  {
    id: 'ropa-142',
    name: 'IMG-20260413-WA0037',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👚',
    category: 'Moda',
    gradientKey: 'pib-6',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0037.jpg',
  },
  {
    id: 'ropa-143',
    name: 'IMG-20260413-WA0038',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👕',
    category: 'Moda',
    gradientKey: 'pib-7',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0038.jpg',
  },
  {
    id: 'ropa-144',
    name: 'IMG-20260413-WA0039',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👖',
    category: 'Moda',
    gradientKey: 'pib-8',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0039.jpg',
  },
  {
    id: 'ropa-145',
    name: 'IMG-20260413-WA0040',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧥',
    category: 'Moda',
    gradientKey: 'pib-1',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0040.jpg',
  },
  {
    id: 'ropa-146',
    name: 'IMG-20260413-WA0041',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🧣',
    category: 'Moda',
    gradientKey: 'pib-2',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0041.jpg',
  },
  {
    id: 'ropa-147',
    name: 'IMG-20260413-WA0042',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '👔',
    category: 'Moda',
    gradientKey: 'pib-3',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0042.jpg',
  },
  {
    id: 'ropa-148',
    name: 'IMG-20260413-WA0043',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩱',
    category: 'Moda',
    gradientKey: 'pib-4',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0043.jpg',
  },
  {
    id: 'ropa-149',
    name: 'IMG-20260413-WA0044',
    description: 'Peça da coleção Ropa.',
    priceInCents: 4990,
    oldPriceInCents: null,
    emoji: '🩲',
    category: 'Moda',
    gradientKey: 'pib-5',
    badge: null,
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Único'],
    rating: 0,
    reviews: 0,
    imageUrl: '/static/products/Ropa/IMG-20260413-WA0044.jpg',
  },
];
